apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbo-demo-consumer-v1
  namespace: dubbo-self
  labels:
    app: dubbo-demo-consumer
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo-demo-consumer
      version: v1
  template:
    metadata:
      labels:
        app: dubbo-demo-consumer
        version: v1
#      annotations:
#        sidecar.istio.io/rewriteAppHTTPProbers: "false" # 防止 istio 重写 http 探针到envoy
    spec:
      imagePullSecrets:
      - name: aliyun
      containers:
      - name: dubbo-demo-consumer
        image: registry.cn-hangzhou.aliyuncs.com/sky11961677/dev:dubbo-consumer-0.0.1-SNAPSHOT
        imagePullPolicy: Always #Always 、Never 、IfNotPresent
         #command: ["java","-jar","dubbo-consumer-0.0.1-SNAPSHOT.jar"]
        env:
        - name: JAVA_TOOL_OPTIONS #增加opentelemetry javaagent
          value: "-javaagent:/dubbo-consumer/opentelemetry-javaagent.jar -Dotel.resource.attributes=service.name=dubbo-demo-consumer -Dotel.traces.exporter=otlp -Dotel.metrics.exporter=otlp -Dotel.propagators=b3 -Dotel.exporter.otlp.endpoint=http://otel-collector.istio-system.svc.cluster.local:4317"
        ports:
        - name: grpc-tri
          containerPort: 20881
          protocol: TCP
        - name: http-consumer
          containerPort: 8081
          protocol: TCP
#        resources:
#          limits:
#            cpu: "500m"
#            memory: 1Gi
#          requests:
#            cpu: "500m"
#            memory: 1Gi
        livenessProbe: #容器存活探针
          httpGet: # 定义 http get 探针 ， 或 TCP Socket 或Exec
            path: /dubbo-demo-consumer/actuator/health  # 指定路径和端口号
            port: 8081
          initialDelaySeconds: 50 # 初次探测延迟 50s
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe: #就绪探针，防止pod启动后就暴露给service
          exec:
            command:
              - ls
              - /var/log
#        startupProbe:
#          httpGet:
#            path: /dubbo-demo-consumer/actuator/health
#            port: http-health
#          failureThreshold: 30
#          initialDelaySeconds: 50
#          periodSeconds: 10
#          timeoutSeconds: 3