apiVersion: apps/v1
kind: Deployment  #资源类型
metadata: #元数据
  name: dubbo-demo-provider-v1
  namespace: dubbo-self #所属namespace
  labels:
    app: dubbo-demo-provider
    version: v1
spec:
  replicas: 1 #pod 实例的期望数
  selector: # 决定 rc 的操作对象，可省略。必须与模板 label 匹配，否则 `selector` does not match template `labels`
    matchLabels:
      app: dubbo-demo-provider
      version: v1
  template:
    metadata:
      labels:
        app: dubbo-demo-provider
        version: v1
#      annotations:
#        sidecar.istio.io/rewriteAppHTTPProbers: "false" #防止 istio 重写 http 探针到envoy
    spec:
      imagePullSecrets:
      - name: aliyun
      containers:
      - name: dubbo-demo-provider
        image: registry.cn-hangzhou.aliyuncs.com/sky11961677/dev:dubbo-provider-0.0.1-SNAPSHOT
        imagePullPolicy: Always
        env:
        - name: JAVA_TOOL_OPTIONS #增加opentelemetry javaagent
          value: "-javaagent:/dubbo-provider/opentelemetry-javaagent.jar -Dotel.resource.attributes=service.name=dubbo-demo-provider -Dotel.traces.exporter=otlp -Dotel.metrics.exporter=otlp -Dotel.propagators=b3 -Dotel.exporter.otlp.endpoint=http://otel-collector.istio-system.svc.cluster.local:4317"
         #command: ["java","-jar","dubbo-provider-0.0.1-SNAPSHOT.jar"]
        ports:
        - name: grpc-tri
          containerPort: 20880  #对外暴露端口
          protocol: TCP # supported values: "SCTP", "TCP", "UDP"
        - name: http-provider
          containerPort: 8080
          protocol: TCP
#        resources:
#          limits:
#            cpu: "500m"
#            memory: 1Gi
#          requests:
#            cpu: "500m"
#            memory: 1Gi
        livenessProbe: #容器存活探针
          httpGet: # 定义 http get 探针 ， 或 TCP Socket 或Exec
            path: /dubbo-demo-provider/actuator/health  # 指定路径和端口号
            port: 8080
          initialDelaySeconds: 50 # 初次探测延迟 50s
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe: #就绪探针，防止pod启动后就暴露给service
          exec:
            command:
              - ls
              - /var/log
#        startupProbe:
#          httpGet:
#            path: /dubbo-demo-provider/actuator/health
#            port: http-health
#          failureThreshold: 30
#          initialDelaySeconds: 50
#          periodSeconds: 10
#          timeoutSeconds: 3

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbo-demo-provider-v2
  namespace: dubbo-self
  labels:
    app: dubbo-demo-provider
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo-demo-provider
      version: v2
  template:
    metadata:
      labels:
        app: dubbo-demo-provider
        version: v2
    spec:
      imagePullSecrets:
      - name: aliyun
      containers:
      - name: dubbo-demo-provider
        image: registry.cn-hangzhou.aliyuncs.com/sky11961677/dev:dubbo-provider-0.0.2-SNAPSHOT
        imagePullPolicy: Always
        env:
        - name: JAVA_TOOL_OPTIONS #增加opentelemetry javaagent
          value: "-javaagent:/dubbo-provider/opentelemetry-javaagent.jar -Dotel.resource.attributes=service.name=dubbo-demo-provider -Dotel.traces.exporter=otlp -Dotel.metrics.exporter=otlp -Dotel.propagators=b3 -Dotel.exporter.otlp.endpoint=http://otel-collector.istio-system.svc.cluster.local:4317"
         #command: ["java","-jar","dubbo-provider-0.0.1-SNAPSHOT.jar"]
        ports:
        - name: grpc-tri
          containerPort: 20880
          protocol: TCP
        - name: http-provider
          containerPort: 8080
          protocol: TCP
#        resources:
#          limits:
#            cpu: "500m"
#            memory: 1Gi
#          requests:
#            cpu: "500m"
#            memory: 1Gi
        livenessProbe: #容器存活探针
          httpGet: # 定义 http get 探针 ， 或 TCP Socket 或Exec
            path: /dubbo-demo-provider/actuator/health  # 指定路径和端口号
            port: 8080
          initialDelaySeconds: 50 # 初次探测延迟 50s
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe: #就绪探针，防止pod启动后就暴露给service
          exec:
            command:
              - ls
              - /var/log
#        startupProbe:
#          httpGet:
#            path: /dubbo-demo-provider/actuator/health
#            port: http-health
#          failureThreshold: 30
#          initialDelaySeconds: 50
#          periodSeconds: 10
#          timeoutSeconds: 3
