namePrefix: prod-
commonLabels:
  variant: prod
commonAnnotations:
  note: Hello, This is prod!
patchesStrategicMerge:
  - destination-rule.yaml
patchesJson6902:
  - target:
      group: networking.istio.io
      version: v1alpha3
      kind: VirtualService
      name: dubbo-demo-provider-vs
      namespace: dubbo-self
    path: vm-provider-patch.json
  - target:
      group: networking.istio.io
      version: v1alpha3
      kind: VirtualService
      name: dubbo-demo-consumer-vs
      namespace: dubbo-self
    path: vm-consumer-patch.json
  - target:
      group: networking.istio.io
      version: v1alpha3
      kind: VirtualService
      name: dubbo-self-ingress-gateway-vm
      namespace: dubbo-self
    path: vm-ingress-patch.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: prod-dubbo-self