spring:
  application:
    name: dubbo-consumer-application

dubbo:
  application:
    name: dubbo-consumer-application
    compiler: javassist
  protocol:
    name: tri
    port: 20881
    serialization: protobuf
  registry:
    address: N/A

server:
  port: 8081
  servlet:
    context-path: /dubbo-demo-consumer

logging:
  pattern:
    level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} %5p


management:
  endpoint:
    health:
      show-details: always  # health显示详细信息
  endpoints:
    web:
      exposure:
        include: "*" #暴露全部endpoint
      base-path: /actuator  #默认endpoint前缀，可修改为 /
